name: Makefile CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: pablomk7/libctrpf:0.8.0
      options: --user 1001

    steps:
    - name: clone
      uses: actions/checkout@v6
      with:
        submodules: recursive
      
    - name: build
      run: make
      
    - name: upload release
      uses: actions/upload-artifact@v6
      with:
        name: release
        path: ./*-release.3gx

    - name: upload debug
      uses: actions/upload-artifact@v6
      with:
        name: debug
        path: ./*-debug.3gx
